### PR TITLE
Add randomized user-agent

### PR DESCRIPTION
**Pull request by iamtakingithard**
https://github.com/TeamPiped/piped-proxy/issues/24

### CODE REVIEW

**Comment by FireMasterK** [comment]
I don't want to do this for the following reasons:
1. The user agent is set on initialization, and is not randomized per request.
2. We use the user-agent from `privacy.resistFingerprinting`, to appear the same as any Tor browser/Firefox user.
3. The [library's user agents](https://github.com/a11ywatch/ua_generator/blob/1b738b0f3dacce9e584784990cb88b2a865ee9d4/ua_generator/src/ua_list.rs#L3-L11) are extremely outdated.
4. The library isn't really updated on crates.io anymore, only git.

**Comment by iamtakingithard** [comment]
So, if i get it correctly Firefox user-agents would be necessary because they support `privacy.resistFingerprinting`? At least, I would suggest just to update hardcoded Firefox's user-agent.

**Comment by FireMasterK** [comment]
Updated in 6dc1c6a896164ca2994a880d8e65ed9b88675870, unfortunately, this process can't be done easily/automatically since we need to do this in the Backend, reqwest4j, and here simultaneously!

**Comment by iamtakingithard** [comment]
Gotcha, I will close PR then.

**Pull request closed without merging**
